# Generated by Django 3.0.1 on 2020-01-28 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20200128_0721'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Orders',
        ),
    ]
